export const WS_CONNECT = "WS_CONNECT";
export const WS_DISCONNECT = "WS_DISCONNECT";
export const WS_NEW_MESSAGE = "WS_NEW_MESSAGE";

export const WS_SET_CONNECTED = "WS_SET_CONNECTED";
export const WS_SET_DISCONNECTED = "WS_SET_DISCONNECTED";

export const WS_CREATE_USER = "WS_CREATE_USER";

export const WS_POST_LOCATION = "WS_POST_LOCATION";
